
spring:
  datasource:
    url: jdbc:mysql:///mydb?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver



server:
  port: 9091
dubbo:
  registry:
    address: 106.54.50.236:2181
    protocol: zookeeper
  protocol:
    port: 20881
  application:
    name: book-web